### ISSUE TITLE
Coveralls integration is broken / flaky

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/python-fastpurge#12]
Coveralls test runs for this project in Travis started to fail in the last day:

```
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
Traceback (most recent call last):
  File "/home/travis/build/release-engineering/python-fastpurge/.tox/cov-travis/bin/coveralls", line 10, in <module>
    sys.exit(main())
  File "/home/travis/build/release-engineering/python-fastpurge/.tox/cov-travis/lib/python3.5/site-packages/coveralls/cli.py", line 80, in main
    log.info(result['url'])
KeyError: 'url'
```

Not sure what the cause of this is, but it's probably not the fault of this project. 
 In https://github.com/lemurheavy/coveralls-public/issues/1264 we can see that many others hit the same issue in recent days and started to disable coveralls due to this.

The problem might go away with no further action needed from us.  If it persists, we'll have to disable coveralls.

**Comment by rohanpm** [comment]
Fixed now: https://travis-ci.org/release-engineering/python-fastpurge/jobs/495699953

There's an explanation in https://github.com/lemurheavy/coveralls-public/issues/1264, it was a problem in communication between coveralls and Travis.
