### ISSUE TITLE
depends on broken version more-executors>=1.19.1

### ISSUE THREAD

**Issue by midnightercz** [release-engineering/python-fastpurge#16]
When running on OS where python-futures (or futures via pip) is not installed, client fails with import error

```
[ ~]$ python
Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fast_purge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named fast_purge
>>> import fastpurge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/fastpurge/__init__.py", line 1, in <module>
    from fastpurge._client import FastPurgeClient, FastPurgeError
  File "/usr/lib/python2.6/site-packages/fastpurge/_client.py", line 11, in <module>
    from more_executors.futures import f_sequence
ImportError: No module named futures
>>> 
>>> import more_executors
>>> import more_executors.futures
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named futures
>>> 

```

Problem above seems to be fixed in 
https://github.com/rohanpm/more-executors/tree/v2.0.0

**Comment by midnightercz** [comment]
Actually not issue, I had somehow installed some old version locally, it works fine with 1.19.1
